/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.13/userguide/multi_project_builds.html in the Gradle documentation.
 */


pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        // 1) 오픈소스를 위한 중앙 저장소
        mavenCentral()
        //2) 사내 Nexus 저장소
        val allowInsecure = providers.gradleProperty("nexus.allowInsecure")
            .orNull
            ?.toBoolean() ?: false 
        providers.gradleProperty("nexus.releasesUrl").orNull?.let { url ->
            maven(url) {
                name = "podosoftware-nexus-releases"
                isAllowInsecureProtocol = allowInsecure 
            }
        } 
    }
}
plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.9.0"
}
rootProject.name = "studio-one-api-server"
